### PR TITLE
Use hubot's name in shell adapter

### PR DESCRIPTION
**Pull request by mal**
It feels weird to name the bot during setup and then have it called `Hubot` regardless in local testing. So lets not do that anymore :smile_cat:

### CODE REVIEW

**Comment by technicalpickles** [comment]
Good point. I suspect this came over from original generator, that only used the name for a directory to create, and didn't actually have templates.

**Comment by technicalpickles** [comment]
The name does get used in the Procfile. I guess both wouldn't hurt, but if Procfile is just calling bin, I think we can just remove it from bin.

**Comment by technicalpickles** [comment]
> I think we can just remove it from bin.

Actually, I mean I think we can remove it from Procfile, as it just calls bin/hubot itself, which would have the name.

**Comment by technicalpickles** [comment]
I was curious what would happen if you called `bin/hubot --name someothername`, since that would under the hood call `node_modules\.bin\hubot.cmd --name originalbotname --name someothername`, and it seems to correctly use only the last specified name.

**Comment by mal** [comment]
Yup, tried that myself, useful for when you're generating examples and you want the bot to represent itself as the generic `hubot`.

**Comment by technicalpickles** [comment]
Released in v0.2.5, thanks!

**Pull request merged**
